# ========================================================
# ThanhTV VPS Configuration File
# Version: 2.0
# ========================================================

default_domain: demo.local
admin_email: admin@demo.local
timezone: Asia/Ho_Chi_Minh

php_versions: "7.4 8.1 8.2 8.3"
default_php: "8.2"

nginx_worker_processes: auto
nginx_client_max_body_size: 128M
nginx_enable_gzip: true
nginx_enable_brotli: true

mysql_random_password: true
mysql_root_password: ""
mysql_default_charset: utf8mb4
mysql_default_collation: utf8mb4_unicode_ci

redis_enabled: true
redis_port: 6379
redis_maxmemory: 256mb
redis_maxmemory_policy: allkeys-lru

nodejs_enabled: false
nodejs_versions: "18 20"
nodejs_default_version: 20

filemanager_enabled: true
filemanager_port: 8080
filemanager_username: admin

ssl_auto_ssl: true
ssl_email: ""

backup_enabled: false
backup_schedule: "30 2 * * *"
backup_keep_days: 7
backup_path: /opt/backups

security_fail2ban: true
security_ufw_firewall: true
security_ssh_port: 22
security_disable_root_ssh: false

monitoring_enable_logs: true
monitoring_log_rotation: true
